name: flutter_icalendar_signage
description: Flutter ICalendar Signage.
version: 1.0.0

environment:
  sdk: '>=2.18.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  intl: ^0.18.1
  hooks_riverpod: ^2.3.10
  http: ^0.13.6
  icalendar_parser: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


